Node v2 Update [semver:major] (#24)
Motivation:
Clean up the Node Orb experience to showcase our best practices and modernized conventions. This update aims to re-approach the Node orb for better user experience.

This update is a near-complete re-write aimed at making the commands of this orb less ambiguous, more useful, and easier to use.

Commands
Install

A singular install command that makes use of parameters to install NodeJS + NPM and optionally Yarn.
Install-npm

Left largely unchanged. This functionality could be baked into the install command internally but it may prove useful to allow the user to install their package manager separately easily if desired.
Install-yarn

Left largely unchanged. This functionality could be baked into the install command internally but it may prove useful to allow the user to install their package manager separately easily if desired.
Install-packages

A new command meant to replace both the old "with cache" and "install deps" commands.
This naming convention makes more intuitive sense for node developers.
With cache is a default parameter.
Uses npm ci by default
With Splitting

Removed the with_splitting job.
The syntax was highly complex.
Test splitting in Node.JS is not similar to other languages given you do not typically call the testing tool directly but rather run an NPM script. Depending on the testing tool you are using, the inputs can vary. This must be setup manually.
Executor
The default executor has been set to https://hub.docker.com/r/cimg/node, our cimg Node image at version "13.11", the current latest version of node. LTS versions are of course available and can be set via the version parameter.

Test
The node/test job will automatically test your NodeJS project quickly and easily with caching included.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,318 +1,135 @@
 version: 2.1
 
 orbs:
-  build-tools: circleci/build-tools@2.6.2
-  jq: circleci/jq@volatile
-  node: circleci/node@dev:alpha
-  orb-tools: circleci/orb-tools@8.27.3
+  node: circleci/node@<<pipeline.parameters.dev-orb-version>>
+  orb-tools: circleci/orb-tools@9.0
 
-jobs:
-  test:
-    parameters:
-      executor:
-        type: executor
-        default: node/default
+# Pipeline parameters
+parameters:
+  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
+  # job, by default.
+  run-integration-tests:
+    type: boolean
+    default: false
+  dev-orb-version:
+    type: string
+    default: "dev:alpha"
 
-      node-version:
-        type: string
-        default: latest
-
-      node-alpine-version:
-        type: string
-        default: nodejs-current
-
-      npm-version:
-        type: string
-        default: latest
-
-      yarn-version:
-        type: string
-        default: ""
-
-    executor: <<parameters.executor>>
-    steps:
-      - checkout
-      - build-tools/install-ci-tools
-
-      - node/install:
-          node-version: <<parameters.node-version>>
-          node-alpine-version: <<parameters.node-alpine-version>>
-          npm-version: <<parameters.npm-version>>
-          yarn-version: <<parameters.yarn-version>>
-          debug: true
-
-# yaml anchor filters
-integration-dev_filters: &integration-dev_filters
-  branches:
-    ignore: /.*/
-  tags:
-    only: /integration-.*/
-
-integration-master_filters: &integration-master_filters
-  branches:
-    ignore: /.*/
-  tags:
-    only: /master-.*/
-
-prod-deploy_requires: &prod-deploy_requires
+integration-tests: &integration-tests
   [
-    install-machine-master,
-    install-machine-versioned-master,
-    install-mac-master,
-    install-mac-versioned-master,
-    install-node-master,
-    install-node-versioned-master,
-    install-ubuntu-master,
-    install-ubuntu-versioned-master,
-    install-alpine-master,
-    install-alpine-versioned-master,
-    install-oracle-master,
-    install-oracle-versioned-master
+    integration-test-install-linux,
+    integration-test-install-mac,
+    node-test-job,
+    integration-test-install-linux-latest
   ]
 
+jobs:
+# Install NodeJS into a non-node container.
+  integration-test-install-linux:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - node/install:
+          node-version: "13.11.0"
+          install-yarn: true # Test the install of YARN
+      - run:
+          command: |
+            if ! node --version | grep -q "13"; then
+              echo "Node version 13 not found"
+              exit 1
+            fi
+
+  integration-test-install-linux-latest:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - node/install:
+          node-version: "latest"
+      - run:
+          name: Check that latest NodeJS is installed.
+          command: |
+            NODE_ORB_INSTALL_VERSION=$(curl -Ls -o /dev/null -w %{url_effective} \
+              "https://github.com/nodejs/node/releases/latest" | sed 's:.*/::' | cut -d 'v' -f 2)
+            if ! node --version | grep -q "$NODE_ORB_INSTALL_VERSION"; then
+              echo "Latest Node version = $NODE_ORB_INSTALL_VERSION"
+              echo "Installed version: $(node --version)"
+              exit 1
+            fi
+
+  integration-test-install-mac:
+    macos:
+      xcode: 11.4.0
+    steps:
+      - checkout
+      - node/install:
+          node-version: "13.11.0"
+          install-yarn: true # Test the install of YARN
+      - run:
+          command: |
+            if ! node --version | grep -q "13"; then
+              echo "Node version 13 not found"
+            fi
+
+
 workflows:
+  # This `lint-pack_validate_publish-dev` workflow will run on any commit.
   lint_pack-validate_publish-dev:
+    unless: << pipeline.parameters.run-integration-tests >>
     jobs:
       - orb-tools/lint
+      # pack your orb YAML files to a single orb.yml
+      # validate the orb.yml file to ensure it is well-formed
+      - orb-tools/pack
 
-      - orb-tools/pack:
-          requires: [orb-tools/lint]
-
+      # release dev version of orb, for testing & possible publishing.
+      # orb will be published as dev:alpha and dev:${CIRCLE_SHA1:0:7}.
+      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
+      # https://circleci.com/docs/2.0/managing-api-tokens
+      # store CIRCLE_TOKEN as a project env var or Contexts resource
+      # if using Contexts, add your context below
       - orb-tools/publish-dev:
           orb-name: circleci/node
           context: orb-publishing
-          requires: [orb-tools/pack]
+          requires:
+            - orb-tools/pack
+            - orb-tools/lint
 
-      - orb-tools/trigger-integration-workflow:
+      # trigger an integration workflow to test the
+      # dev:${CIRCLE_SHA1:0:7} version of your orb
+      - orb-tools/trigger-integration-tests-workflow:
           name: trigger-integration-dev
           context: orb-publishing
-          ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
-          requires: [orb-tools/publish-dev]
-          filters:
-            branches:
-              ignore: master
+          requires:
+            - orb-tools/publish-dev
 
-      - orb-tools/trigger-integration-workflow:
-          name: trigger-integration-master
+  # This `integration-tests_prod-release` workflow will only run
+  # when the run-integration-tests pipeline parameter is set to true.
+  # It is meant to be triggered by the "trigger-integration-tests-workflow"
+  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
+  integration-tests_prod-release:
+    when: << pipeline.parameters.run-integration-tests >>
+    jobs:
+      # your integration test jobs go here: essentially, run all your orb's
+      # jobs and commands to ensure they behave as expected. or, run other
+      # integration tests of your choosing
+      - integration-test-install-linux
+      - integration-test-install-mac
+      - integration-test-install-linux-latest
+      - node/test:
+          name: node-test-job
+          app-dir: "~/project/sample"
+      - orb-tools/dev-promote-prod-from-commit-subject:
+          orb-name: circleci/node
           context: orb-publishing
+          add-pr-comment: true
+          bot-token-variable: GHI_TOKEN
+          bot-user: cpe-bot
+          fail-if-semver-not-indicated: true
+          publish-version-tag: true
           ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
-          tag: master
-          cleanup-tags: true
-          requires: [orb-tools/publish-dev]
+          requires: *integration-tests
           filters:
             branches:
               only: master
-
-  integration-tests_prod-release:
-    jobs:
-      # triggered by non-master branch commits
-      # machine
-      - test:
-          name: install-machine-dev
-          executor: orb-tools/machine
-          filters: *integration-dev_filters
-
-      - test:
-          name: install-machine-versioned-dev
-          executor:
-            name: orb-tools/machine
-            image: circleci/classic:latest
-          node-version: "6.1.0"
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-dev_filters
-
-      # macos
-      - test:
-          name: install-mac-dev
-          executor: orb-tools/macos
-          filters: *integration-dev_filters
-
-      - test:
-          name: install-mac-versioned-dev
-          executor: orb-tools/macos
-          node-version: "8.9.4"
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-dev_filters
-
-      # node
-      - test:
-          name: install-node-dev
-          filters: *integration-dev_filters
-
-      - test:
-          name: install-node-versioned-dev
-          node-version: "8.9.4"
-          npm-version: "6.3.0"
-          yarn-version: "1.15.2"
-          filters: *integration-dev_filters
-
-      # cimg
-      - test:
-          name: install-ubuntu-dev
-          executor: orb-tools/ubuntu
-          filters: *integration-dev_filters
-
-      - test:
-          name: install-ubuntu-versioned-dev
-          executor: orb-tools/ubuntu
-          node-version: "8.9.4"
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-dev_filters
-
-      # alpine
-      - test:
-          name: install-alpine-dev
-          executor: orb-tools/alpine
-          filters: *integration-dev_filters
-
-      - test:
-          name: install-alpine-versioned-dev
-          executor: orb-tools/alpine
-          node-alpine-version: nodejs
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-dev_filters
-
-      # oracle
-      - test:
-          name: install-oracle-dev
-          executor: orb-tools/oracle
-          node-version: "8.9.4"
-          filters: *integration-dev_filters
-
-      - test:
-          name: install-oracle-versioned-dev
-          executor: orb-tools/oracle
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-dev_filters
-
-      # triggered by master branch commits
-      # machine
-      - test:
-          name: install-machine-master
-          executor: orb-tools/machine
-          filters: *integration-master_filters
-
-      - test:
-          name: install-machine-versioned-master
-          executor:
-            name: orb-tools/machine
-            image: circleci/classic:latest
-          node-version: "6.1.0"
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-master_filters
-
-      # macos
-      - test:
-          name: install-mac-master
-          executor: orb-tools/macos
-          filters: *integration-master_filters
-
-      - test:
-          name: install-mac-versioned-master
-          executor: orb-tools/macos
-          node-version: "8.9.4"
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-master_filters
-
-      # node
-      - test:
-          name: install-node-master
-          filters: *integration-master_filters
-
-      - test:
-          name: install-node-versioned-master
-          node-version: "8.9.4"
-          npm-version: "6.3.0"
-          yarn-version: "1.15.2"
-          filters: *integration-master_filters
-
-      # cimg
-      - test:
-          name: install-ubuntu-master
-          executor: orb-tools/ubuntu
-          filters: *integration-master_filters
-
-      - test:
-          name: install-ubuntu-versioned-master
-          executor: orb-tools/ubuntu
-          node-version: "8.9.4"
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-master_filters
-
-      # alpine
-      - test:
-          name: install-alpine-master
-          executor: orb-tools/alpine
-          filters: *integration-master_filters
-
-      - test:
-          name: install-alpine-versioned-master
-          executor: orb-tools/alpine
-          node-alpine-version: nodejs
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-master_filters
-
-      # oracle
-      - test:
-          name: install-oracle-master
-          executor: orb-tools/oracle
-          node-version: "8.9.4"
-          filters: *integration-master_filters
-
-      - test:
-          name: install-oracle-versioned-master
-          executor: orb-tools/oracle
-          npm-version: "6.4.1"
-          yarn-version: "1.15.2"
-          filters: *integration-master_filters
-
-      # patch, minor, or major publishing
-      - orb-tools/dev-promote-prod:
-          name: dev-promote-patch
-          context: orb-publishing
-          orb-name: circleci/node
-          ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
-          cleanup-tags: true
-          requires: *prod-deploy_requires
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /master-patch.*/
-
-      - orb-tools/dev-promote-prod:
-          name: dev-promote-minor
-          context: orb-publishing
-          orb-name: circleci/node
-          ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
-          cleanup-tags: true
-          release: minor
-          requires: *prod-deploy_requires
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /master-minor.*/
-
-      - orb-tools/dev-promote-prod:
-          name: dev-promote-major
-          context: orb-publishing
-          orb-name: circleci/node
-          ssh-fingerprints: 2a:2b:49:ea:64:7d:39:4a:58:17:18:17:b2:5c:f6:a8
-          cleanup-tags: true
-          release: major
-          requires: *prod-deploy_requires
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /master-major.*/
diff --git a/src/commands/install.yml b/src/commands/install.yml
--- a/src/commands/install.yml
+++ b/src/commands/install.yml
@@ -1,5 +1,5 @@
 description: >
-  Install custom versions of Node.js, and optionally NPM/Yarn, in any
+  Install custom versions of NodeJS, and optionally NPM/Yarn, in any
   execution environment (Docker/Linux, macOS, machine) that does not have
   it preinstalled
 
@@ -7,35 +7,16 @@ parameters:
   # node
   node-version:
     type: string
-    default: latest
+    default: ""
     description: >
-      Specific version of Node.js to install. Note: version-selection is
-      not supported for Alpine Linux-based execution environments, as
-      Node.js's Linux binaries are not compiled to run on Alpine. Use the
-      `alpine-version` parameter to select from a limited number of
-      Alpine-based Node.js packages. Otherwise, for a full list of
-      releases, see the following: https://nodejs.org/en/download/releases
-
-  node-alpine-version:
-    type: enum
-    default: nodejs-current
-    enum: [nodejs, nodejs-current]
-    description: >
-      For Alpine Linux users, select a Node.js version: either a current
-      stable release, or a slightly older stable release. For more
-      information, see https://pkgs.alpinelinux.org/packages?name=nodejs*
+      The latest (current) version of NodeJS will be installed unless a version is specified. A full version tag must be specified. Example: "13.11.0"
+      For a full list of releases, see the following: https://nodejs.org/en/download/releases
 
   node-install-dir:
     type: string
     default: /usr/local
     description: >
       Where should Node.js be installed?
-
-  debug:
-    type: boolean
-    default: false
-    description: >
-      Extra output for orb developers
 
   # npm
   install-npm:
@@ -49,14 +30,11 @@ parameters:
     description: >
       Pick a version of NPM to install:
       https://nodejs.org/en/download/releases
-      (Note: NPM version selection is not possible on Alpine Linux;
-      on Alpine, the `npm` Alpine pkg will be installed:
-      https://pkgs.alpinelinux.org/packages?name=npm)
 
   # yarn
   install-yarn:
     type: boolean
-    default: true
+    default: false
     description: Install Yarn?
 
   yarn-version:
@@ -68,22 +46,163 @@ parameters:
       https://github.com/yarnpkg/yarn/releases
 
 steps:
-  - install-node:
-      version: <<parameters.node-version>>
-      alpine-version: <<parameters.node-alpine-version>>
-      install-dir: <<parameters.node-install-dir>>
-      debug: <<parameters.debug>>
+  - run:
+      name: Installing NodeJS <<parameters.node-version>>
+      command: |
+        # PLATFORM CHECK: mac vs. alpine vs. other linux
+
+        SYS_ENV_PLATFORM=linux
+        if uname -a | grep Darwin; then
+          SYS_ENV_PLATFORM=darwin
+        elif cat /etc/issue | grep Alpine; then
+          SYS_ENV_PLATFORM=alpine
+        fi
+
+        # FUNCTIONS
+
+        get_node_version () {
+          if [[ <<parameters.node-version>> == "" || <<parameters.node-version>> == "latest" || <<parameters.node-version>> == "current" ]]; then
+            NODE_ORB_INSTALL_VERSION=$(curl -Ls -o /dev/null -w %{url_effective} \
+              "https://github.com/nodejs/node/releases/latest" | sed 's:.*/::' | cut -d 'v' -f 2)
+            echo "Latest version of Node.js is $NODE_ORB_INSTALL_VERSION"
+          else
+            NODE_ORB_INSTALL_VERSION="<<parameters.node-version>>"
+            echo "Selected version of Node.js is $NODE_ORB_INSTALL_VERSION"
+          fi
+        }
+
+        installation_check () {
+          if command -v node; then
+
+            if node --version | grep "$NODE_ORB_INSTALL_VERSION"; then
+
+              echo "Node.js $NODE_ORB_INSTALL_VERSION is already installed"
+              exit 0
+            else
+              echo "A different version of Node.js is installed ($(node --version)); removing it"
+
+              $SUDO rm -rf "$(command -v node)"
+              $SUDO rm -rf "$(command -v node | sed -E 's|node||')/nodejs"
+
+              $SUDO rm -rf "$(command -v npm)"
+
+              $SUDO rm -rf \
+                /usr/local/lib/node_modules \
+                /usr/local/include/node_modules \
+                /opt/local/lib/node_modules
+
+            fi
+          fi
+        }
+
+        # Install logic per platform
+
+        case $SYS_ENV_PLATFORM in
+          alpine)
+            echo "Install for alpine, or remove"
+          ;;
+          darwin)
+            if ! command -v gpg; then
+              HOMEBREW_NO_AUTO_UPDATE=1 brew install gnupg
+              HOMEBREW_NO_AUTO_UPDATE=1 brew install coreutils
+            fi
+          ;;
+        esac
+
+        if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
+
+          get_node_version
+          installation_check
+
+          # Configure Security Keys for verification of Download
+
+          $SUDO curl \
+            --silent --show-error --location --fail --retry 3 \
+            https://raw.githubusercontent.com/nodejs/node/master/README.md | \
+            grep -E '[A-Z0-9]{40}' | \
+            sed -E 's/gpg --keyserver pool.sks-keyservers.net --recv-keys //g' | \
+            sed -E 's/(`|\$ )//g' > \
+            NODEJS_TRUSTED_RELEASE_KEYS
+
+          cat > KEYSERVERS \<< EOM
+          hkp://p80.pool.sks-keyservers.net:80
+          hkp://ipv4.pool.sks-keyservers.net
+          hkp://pgp.mit.edu:80
+          hkps://ha.pool.sks-keyservers.net
+          hkp://keyserver.ubuntu.com:80
+        EOM
+
+          echo "Importing Node.js trusted release keys..."
+          # https://stackoverflow.com/a/26217767
+          while read key; do
+            for keyserver in $(cat KEYSERVERS); do
+              tempName=$(mktemp)
+              gpg --status-fd 1 \
+                --keyserver "$keyserver" --keyserver-options "timeout=1" \
+                --recv-keys "$key" 1> "$tempName" 2>/dev/null || true
+              if [[ $(grep "^\[GNUPG\:\] IMPORT_OK "[[:digit:]]*" "$key"$" $tempName && \
+                grep "^\[GNUPG\:\] IMPORT_RES 1" $tempName) ]]; then
+                echo "Success! Imported $key from $keyserver"
+                break
+              else
+                continue
+              fi
+            done
+          done < NODEJS_TRUSTED_RELEASE_KEYS
+
+          $SUDO rm -f NODEJS_TRUSTED_RELEASE_KEYS KEYSERVERS
+
+          # Download binary
+          echo Node binary downloaded
+          echo "Downloading: https://nodejs.org/download/release/v$NODE_ORB_INSTALL_VERSION/node-v$NODE_ORB_INSTALL_VERSION-$SYS_ENV_PLATFORM-x64.tar.gz"
+          $SUDO curl -O \
+            --silent --show-error --location --fail --retry 3 \
+            "https://nodejs.org/download/release/v$NODE_ORB_INSTALL_VERSION/node-v$NODE_ORB_INSTALL_VERSION-$SYS_ENV_PLATFORM-x64.tar.gz"
+
+          # Download SHASUMS256 and sig
+          echo Fetching SHASUM256 verification
+          curl -O --silent --show-error --location --fail --retry 3 https://nodejs.org/dist/v$NODE_ORB_INSTALL_VERSION/SHASUMS256.txt
+          curl -O --silent --show-error --location --fail --retry 3 https://nodejs.org/dist/v$NODE_ORB_INSTALL_VERSION/SHASUMS256.txt.sig
+
+          # Verify checksum file sig
+          echo Verifing SHASUM256
+          gpg --verify SHASUMS256.txt.sig SHASUMS256.txt
+
+          # Verify checksum of binary
+          echo Verifing binary checksum
+          grep node-v$NODE_ORB_INSTALL_VERSION-$SYS_ENV_PLATFORM-x64.tar.gz SHASUMS256.txt | sha256sum -c -
+
+          # Install Binary
+          echo Installing Node binary
+          $SUDO tar -xzf "node-v$NODE_ORB_INSTALL_VERSION-$SYS_ENV_PLATFORM-x64.tar.gz" \
+            -C <<parameters.node-install-dir>> \
+            --strip-components=1 --no-same-owner > /dev/null 2>&1
+
+          # Remove tar.gz
+          echo Cleaning up installation file
+          $SUDO rm -f "node-v$NODE_ORB_INSTALL_VERSION-$SYS_ENV_PLATFORM-x64.tar.gz"
+
+          if [[ ! -e <<parameters.node-install-dir>>/bin/nodejs ]]; then
+            $SUDO ln -s <<parameters.node-install-dir>>/bin/node <<parameters.node-install-dir>>/bin/nodejs
+          fi
+
+        # test/verify version
+
+        if node --version | grep "$VERSION" > /dev/null; then
+          echo "Node.js $(node --version) has been installed to $(which node)"
+        else
+          echo "Something went wrong; the specified version of Node.js could not be installed"
+          exit 1
+        fi
 
   - when:
       condition: <<parameters.install-npm>>
       steps:
         - install-npm:
             version: <<parameters.npm-version>>
-            debug: <<parameters.debug>>
 
   - when:
       condition: <<parameters.install-yarn>>
       steps:
         - install-yarn:
             version: <<parameters.yarn-version>>
-            debug: <<parameters.debug>>
