add windows support

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,6 +3,7 @@ version: 2.1
 orbs:
   node: circleci/node@<<pipeline.parameters.dev-orb-version>>
   orb-tools: circleci/orb-tools@9.1
+  windows: circleci/windows@2.4.0
 
 # Pipeline parameters
 parameters:
@@ -32,6 +33,7 @@ executors:
   macos:
     macos:
       xcode: 11.4
+  windows: &windows_executor win/default
 
 jobs:
 # Install NodeJS into a non-node container.
@@ -42,16 +44,30 @@ jobs:
     executor: <<parameters.os>>
     steps:
       - checkout
-      - node/install:
-          node-version: "13.11.0"
-          install-yarn: true # Test the install of YARN
-          yarn-version: "1.22.5"
-      - run:
-          command: |
-            if ! node --version | grep -q "13"; then
-              echo "Node version 13 not found"
-              exit 1
-            fi
+      - unless:
+          condition: &is_windows_executor
+            equal: [<<parameters.os>>, *windows_executor]
+          steps:
+            - node/install: &install_specified_version_install
+                node-version: "13.11.0"
+                install-yarn: true # Test the install of YARN
+                yarn-version: "1.22.5"
+            - run: &install_specified_version_test
+                command: |
+                  if ! node --version | grep -q "13"; then
+                    echo "Node version 13 not found"
+                    exit 1
+                  fi
+                shell: bash.exe
+      - when:
+          condition: *is_windows_executor
+          steps:
+            - node/install:
+                <<: *install_specified_version_install
+                windows: true
+            - run:
+                <<: *install_specified_version_test
+                shell: bash.exe
 
   integration-test-install-latest:
     parameters:
@@ -60,17 +76,28 @@ jobs:
     executor: <<parameters.os>>
     steps:
       - checkout
-      - node/install
-      - run:
-          name: Check that latest NodeJS is installed.
-          command: |
-            NODE_ORB_INSTALL_VERSION=$(nvm ls-remote | tail -n1 | awk '{print $2}')
-            echo "Latest Node version = $NODE_ORB_INSTALL_VERSION"
-            echo "Installed version: $(node --version)"
-            if ! node --version | grep -q "$NODE_ORB_INSTALL_VERSION"; then
-              echo "Error: Installed version is different from the latest version."
-              exit 1
-            fi
+      - unless:
+          condition: *is_windows_executor
+          steps:
+            - node/install
+            - run: &install_latest_test
+                name: Check that latest NodeJS is installed.
+                command: |
+                  NODE_ORB_INSTALL_VERSION=$(nvm ls-remote | tail -n1 | awk '{print $2}')
+                  echo "Latest Node version = $NODE_ORB_INSTALL_VERSION"
+                  echo "Installed version: $(node --version)"
+                  if ! node --version | grep -q "$NODE_ORB_INSTALL_VERSION"; then
+                    echo "Error: Installed version is different from the latest version."
+                    exit 1
+                  fi
+      - when:
+          condition: *is_windows_executor
+          steps:
+            - node/install:
+                windows: true
+            - run:
+                <<: *install_latest_test
+                shell: bash.exe
 
   integration-test-install-lts:
     parameters:
@@ -162,11 +189,11 @@ workflows:
       - integration-test-install-specified-version:
           matrix:
             parameters:
-              os: [linux, macos]
+              os: [linux, macos, windows]
       - integration-test-install-latest:
           matrix:
             parameters:
-              os: [linux, macos]
+              os: [linux, macos, windows]
       - integration-test-install-lts:
           matrix:
             parameters:
diff --git a/src/commands/install-packages.yml b/src/commands/install-packages.yml
--- a/src/commands/install-packages.yml
+++ b/src/commands/install-packages.yml
@@ -7,6 +7,10 @@ parameters:
     enum: ["npm", "yarn"]
     default: "npm"
     description: Select the default node package manager to use.
+  windows:
+    type: boolean
+    default: false
+    description: Whether to run with Windows support or not
   with-cache:
     type: boolean
     default: true
@@ -37,24 +41,30 @@ parameters:
       If true, this cache bucket will only apply to jobs within the same branch.
 
 steps:
-  - run:
-      name: Checking for package.json.
-      working_directory: <<parameters.app-dir>>
-      command: |
-        if [ ! -f "package.json" ]; then
-          echo
-          echo "---"
-          echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
-          echo "---"
-          echo
-          echo "Current directory: $(pwd)"
-          echo
-          echo
-          echo "List directory: "
-          echo
-          ls
-          exit 1
-        fi
+  - unless: << parameters.windows >>
+    steps:
+    - run: &check_package_json
+        name: Checking for package.json
+        command: |
+          if [ ! -f "package.json" ]; then
+            echo
+            echo "---"
+            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
+            echo "---"
+            echo
+            echo "Current directory: $(pwd)"
+            echo
+            echo
+            echo "List directory: "
+            echo
+            ls
+            exit 1
+          fi
+  - when: << parameters.windows >>
+    steps:
+      - run:
+        <<: *check_package_json
+        shell: bash.exe
   - when: # Install packages based on NPM
       condition:
         equal: [npm, << parameters.pkg-manager >>]
@@ -65,16 +75,19 @@ steps:
               - restore_cache:
                   keys:
                     - node-deps-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/package-lock.json" }}
-        - run:
-            name: Installing NPM packages
-            working_directory: <<parameters.app-dir>>
-            command: |
-              if [[ ! -z "<< parameters.override-ci-command >>" ]]; then
-                echo "Running override package installation command:"
-                << parameters.override-ci-command >>
-              else
-                npm ci
-              fi
+        - when: << parameters.override-ci-command >>
+          steps:
+            - run: &install_npm_packages
+                name: Installing NPM packages
+                working_directory: <<parameters.app-dir>>
+                command: |
+                    echo "Running override package installation command:"
+                    << parameters.override-ci-command >>
+        - when: << parameters.override-ci-command >>
+          steps:
+            - run:
+                <<: *install_npm_packages
+                command: npm ci
         - when: # cache enabled, save cache
             condition: << parameters.with-cache >>
             steps:
@@ -103,16 +116,18 @@ steps:
              - restore_cache:
                 keys:
                   - node-deps-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "<<parameters.app-dir>>/yarn.lock" }}
-        - run:
-            name: Installing YARN packages
-            working_directory: <<parameters.app-dir>>
-            command: |
-              if [[ ! -z "<< parameters.override-ci-command >>" ]]; then
-                echo "Running override package installation command:"
-                << parameters.override-ci-command >>
-              else
-                yarn install --frozen-lockfile
-              fi
+        - unless:
+            condition: << parameters.override-ci-command >>
+            steps:
+              - run: &install_yarn_packages
+                name: Installing YARN packages
+                command: yarn install --frozen-lockfile
+        - when:
+            condition: << parameters.override-ci-command >>
+            steps:
+              - run:
+                  <<: *install_npm_packages
+                  command: << parameters.override-ci-command >>
         - when: # cache enabled, save cache
             condition: << parameters.with-cache >>
             steps:
