Error if no package.json file. [semver:patch] (#26)
* Error if no package.json file.

* refer to package.json via relative path rather than parameter absolute

diff --git a/src/commands/install-packages.yml b/src/commands/install-packages.yml
--- a/src/commands/install-packages.yml
+++ b/src/commands/install-packages.yml
@@ -45,6 +45,20 @@ steps:
       name: Installing Node Modules.
       working_directory: <<parameters.app-dir>>
       command: |
+        if [ ! -f "package.json" ]; then
+          echo
+          echo "---"
+          echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
+          echo "---"
+          echo
+          echo "Current directory: $(pwd)"
+          echo
+          echo
+          echo "List directory: "
+          echo
+          ls
+          exit 1
+        fi
         case << parameters.pkg-manager >> in
           npm)
             if [[ << parameters.override-ci >> ]]; then
